#!/bin/bash

#
ENV="NODE_ENV=production DEBUG=carcass:*"

# Forever outputs
PID_DIR=~/.forever/pids
LOG_DIR=~/.forever

#
USERNAME=`whoami`

#
as_user() {
  ME=`whoami`
  if [ $ME == $USERNAME ]; then
    bash -lc "$1"
  else
    su -l $USERNAME -c "$1"
  fi
}

#
start() {
  echo "Starting"
  pushd $SOURCE_DIR
  pidFile="$PID_DIR/$NAME.pid"
  logFile="$LOG_DIR/$NAME.log"
  as_user "$ENV \
    forever start \
    --command=$COMMAND \
    --pidFile=$pidFile \
    --logFile=$logFile --append \
    $SCRIPT"
  popd
}

#
stop() {
  echo "Stopping"
  as_user "forever stop $SCRIPT"
}

#
restart() {
  stop
  start
}

#
run() {
  if [ $2 ]; then
    . $2
  fi

  case $1 in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart|reload)
      restart
      ;;
    *)
      echo >&2 "Usage: $0 <start|stop|restart> CONFIGURATION-FILE"
      exit 1
      ;;
    esac
}
